// index.js
import Layout from '@/components/Layout';
import AnimatedText from '@/components/AnimatedText';
import Head from 'next/head';
import Image from 'next/image';
import profilePic from '../../public/images/profile/developer-pic-1.png';
import Link from 'next/link';
import {LinkArrow} from '@/components/Icons'
import AfricaMap from '@/components/AfricaMap'
import lightBulb from "../../public/images/svgs/lightbulb.svg"
import TransitionEffect from '@/components/TransitionEffect'

export default function Home() {
  const text = 'For Visionary Creators ...';
  
  return (
    <>
      <Head>
        <title>My React starter</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:pt-16 sm:pt-4'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2 md:w-full'>
              <Image src={profilePic} alt='Mbegu' className='w-full h-auto lg:hidden md:inline-block md:w-full' 
              priority
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText
                text={text}
                className='text-5xl text-left xl:text-4xl lg:text-center lg:text-4xl md:text-4xl sm:text-2xl' // Adjust text size here
              />
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
                Blah blah
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="#"
                className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg
                font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent
                hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base"
                >
                Launchpad <LinkArrow className={"w-6 ml-1"}/>

                </Link>
                <Link href="/sign"
                className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                >Register</Link>
              </div>
            </div>
          </div>
        </Layout>

        <AfricaMap />

        <div className='absolute right-8 bottom-8 inline-block w-24 md:hidden'>
          <Image src={lightBulb} alt="mbegu_idea" className='w-full h-auto'/>
        </div>
      </main>
    </>
  );
}
